/**
 * GENERATED by `packages/web-tools/scripts/pin-uv.mjs` — do not edit by hand.
 * Bump with `node scripts/pin-uv.mjs <version>`; CI runs `--check`.
 *
 * uv 0.11.28, every build the release publishes. Each sha256 comes from the
 * release's `sha256.sum` (sha256 8ac816bcc3f8d676ac92be79534f924143a8be1c886100f21c51eaeb7189ff34)
 * and was required to equal GitHub's own digest for the asset. `minGlibc` is the
 * oldest glibc the release's `uv-installer.sh` (sha256 b7b3fe80cad1142a2a5794050b7db7b3291d1bac1423b0732571dd9366e8ca8b)
 * accepts for that build.
 */
import type { UvPin } from './uv-platform.js';

export const PINNED_UV: UvPin = {
  version: '0.11.28',
  assets: [
    {
      target: 'aarch64-apple-darwin',
      assetName: 'uv-aarch64-apple-darwin.tar.gz',
      sha256: '33540eb7c883ab857eff79bd5ac2aa31fe27b595abecb4a9c003a2c998447232',
      bytes: 22568053,
    },
    {
      target: 'aarch64-pc-windows-msvc',
      assetName: 'uv-aarch64-pc-windows-msvc.zip',
      sha256: '3248109afad3ec59baad299d324ff53de17e2d9a3b3e21580ffd26744b11e036',
      bytes: 23878916,
    },
    {
      target: 'aarch64-unknown-linux-gnu',
      assetName: 'uv-aarch64-unknown-linux-gnu.tar.gz',
      sha256: '03e9fe0a81b0718d0bc84625de3885df6cc3f89a8b6af6121d6b9f6113fb6533',
      bytes: 24689886,
      minGlibc: '2.28',
    },
    {
      target: 'aarch64-unknown-linux-musl',
      assetName: 'uv-aarch64-unknown-linux-musl.tar.gz',
      sha256: 'da10cdfa7d92212b7acb62021a0fd61bcf8580c58c3632ec915d10c3a1a7906b',
      bytes: 24563837,
    },
    {
      target: 'arm-unknown-linux-musleabihf',
      assetName: 'uv-arm-unknown-linux-musleabihf.tar.gz',
      sha256: '955f9697d4781cf4dfc62d9442a49f3e57861f19405a981ffe9fdc0d18e0a31a',
      bytes: 24902218,
    },
    {
      target: 'armv7-unknown-linux-gnueabihf',
      assetName: 'uv-armv7-unknown-linux-gnueabihf.tar.gz',
      sha256: 'b7cddaad27cd531096e88e64de863f7e37c6fedde11c97595060e6503544d120',
      bytes: 24492062,
      minGlibc: '2.17',
    },
    {
      target: 'armv7-unknown-linux-musleabihf',
      assetName: 'uv-armv7-unknown-linux-musleabihf.tar.gz',
      sha256: 'eb00e0f246d278133df6a55b5d3534a49f051a7dfc276f640b66504c091167f6',
      bytes: 24433357,
    },
    {
      target: 'i686-pc-windows-msvc',
      assetName: 'uv-i686-pc-windows-msvc.zip',
      sha256: '01975deb06072edfc1f18435c25737d8d378dc849b918cd580768ab3b7641e85',
      bytes: 23382175,
    },
    {
      target: 'i686-unknown-linux-gnu',
      assetName: 'uv-i686-unknown-linux-gnu.tar.gz',
      sha256: 'f8d01e918dd4d5eabdd4caee78e8adbc3993a70f3b82395fa6b23fcf791925d9',
      bytes: 26193950,
      minGlibc: '2.17',
    },
    {
      target: 'i686-unknown-linux-musl',
      assetName: 'uv-i686-unknown-linux-musl.tar.gz',
      sha256: 'c869415e44e13000d9daae15cec7bcfaf0735915a8d6e66402d459f6bed35710',
      bytes: 25423736,
    },
    {
      target: 'powerpc64le-unknown-linux-gnu',
      assetName: 'uv-powerpc64le-unknown-linux-gnu.tar.gz',
      sha256: 'b634b6f26a036d112914c2d6d7ae1944bf8f4a6dfed6e19a22b35e5d91f168fb',
      bytes: 26989966,
      minGlibc: '2.17',
    },
    {
      target: 'riscv64gc-unknown-linux-gnu',
      assetName: 'uv-riscv64gc-unknown-linux-gnu.tar.gz',
      sha256: 'be7473dc29ee88bd260e30642faa5ba6dccd7d4493012077873b293c377ab546',
      bytes: 25860874,
      minGlibc: '2.31',
    },
    {
      target: 'riscv64gc-unknown-linux-musl',
      assetName: 'uv-riscv64gc-unknown-linux-musl.tar.gz',
      sha256: '4a9e553d8a62c42600d5c2874b7c2f728c03d4310d72ed7351edbee8ed6a71b4',
      bytes: 25728511,
    },
    {
      target: 's390x-unknown-linux-gnu',
      assetName: 'uv-s390x-unknown-linux-gnu.tar.gz',
      sha256: 'f5ed9d2aed566e11ffc3f1f7ab5b4049dfbfcb04c326ce2ed5bbf42069d62b27',
      bytes: 26287549,
      minGlibc: '2.17',
    },
    {
      target: 'x86_64-apple-darwin',
      assetName: 'uv-x86_64-apple-darwin.tar.gz',
      sha256: '2ad79983127ffca7d77b77ce6a24278d7e4f7b817a1acf72fea5f8124b4aac5e',
      bytes: 24355900,
    },
    {
      target: 'x86_64-pc-windows-msvc',
      assetName: 'uv-x86_64-pc-windows-msvc.zip',
      sha256: '0a23463216d09c6a72ff80ef5dc5a795f07dc1575cb84d24596c2f124a441b7b',
      bytes: 25568726,
    },
    {
      target: 'x86_64-unknown-linux-gnu',
      assetName: 'uv-x86_64-unknown-linux-gnu.tar.gz',
      sha256: 'e490a6464492183c5d4534a5527fb4440f7f2bb2f228162ad7e4afe076dc0224',
      bytes: 26411870,
      minGlibc: '2.17',
    },
    {
      target: 'x86_64-unknown-linux-musl',
      assetName: 'uv-x86_64-unknown-linux-musl.tar.gz',
      sha256: 'f02146b371c35c287d860f003ece7345c86e358a3fd70a9b63700cd141ee7fb4',
      bytes: 26595337,
    },
  ],
};
