/**
 * WHICH uv BUILD THIS MACHINE GETS.
 *
 * uv publishes one archive per Rust target triple (`uv-x86_64-pc-windows-msvc.zip`,
 * `uv-aarch64-unknown-linux-gnu.tar.gz`, …). Before this module the app knew
 * exactly one of them — the macOS arm64 tarball — so every Python feature on a PC
 * (gen modules, ComfyUI, the office pipeline, vLLM, 3D) would have fetched a Mac
 * binary and failed (crossplatform.md §2.4 A1).
 *
 * The rules mirror the release's own installer script (`uv-installer.sh`), so
 * the app and `curl … | sh` agree on what a given machine should run:
 *
 *   - macOS: the arm64 build on Apple Silicon — also for an x64 process running
 *     under Rosetta, which the installer detects the same way (`sysctl
 *     hw.optional.arm64`). An x86_64 uv would provision x86_64 Pythons, and the
 *     MLX stack has no x86_64 wheels.
 *   - Windows: the `.zip` for the process architecture (x64, arm64, ia32); the
 *     binary inside is `uv.exe`.
 *   - Linux: the glibc (`-gnu`) build when the host runs glibc at least as new as
 *     the build needs (the minimum is read from the installer script per release,
 *     see `scripts/pin-uv.mjs`); otherwise the fully static musl build, which runs
 *     on any Linux. A host whose libc cannot be read also gets the static build.
 *
 * Selection is pure (a {@link UvHost} in, a target out) so every row is unit-
 * tested on this Mac; {@link detectUvHost} is the only part that looks at the
 * real machine, and its probes are injectable.
 *
 * Plain Node only; imports nothing electron-specific.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync } from 'node:fs';
import { PINNED_UV } from './uv-pins.js';

/** A Rust target triple uv publishes a build for, e.g. `x86_64-pc-windows-msvc`. */
export type UvTarget = string;

/** How a release archive is packed. */
export type UvArchiveKind = 'tar.gz' | 'zip';

/** One pinned, downloadable uv build. Generated by `scripts/pin-uv.mjs`. */
export interface UvAsset {
  readonly target: UvTarget;
  /** Release asset filename, e.g. `uv-x86_64-pc-windows-msvc.zip`. */
  readonly assetName: string;
  /** Lowercase hex sha256 of the archive, from the release's `sha256.sum`. */
  readonly sha256: string;
  /** Archive size in bytes (from the GitHub releases API). */
  readonly bytes: number;
  /**
   * glibc builds only: the oldest glibc the build runs on (`major.minor`), as the
   * release's installer script checks it. Older hosts get the musl build.
   */
  readonly minGlibc?: string;
}

/** Every build of one uv version the app can install. */
export interface UvPin {
  readonly version: string;
  readonly assets: readonly UvAsset[];
}

/** The one build {@link ensureUv} installs: an asset resolved for a host. */
export interface UvRelease {
  readonly version: string;
  readonly target: UvTarget;
  /** Release asset filename (also the download URL's last segment). */
  readonly assetName: string;
  /** The executable inside the archive: `uv.exe` on Windows, `uv` elsewhere. */
  readonly binName: 'uv' | 'uv.exe';
  readonly archive: UvArchiveKind;
  /** Lowercase hex sha256 the download must match. Always verified. */
  readonly sha256: string;
  readonly bytes?: number;
}

/** What asset selection needs to know about a machine. */
export interface UvHost {
  /** `process.platform`. */
  readonly platform: string;
  /** `process.arch`: `x64`, `arm64`, `ia32`, `arm`, `ppc64`, `riscv64`, `s390x`, … */
  readonly arch: string;
  /** Linux: the C library. `undefined` = could not tell (the static build is used). */
  readonly libc?: 'glibc' | 'musl';
  /** Linux + glibc: the runtime glibc version, e.g. `2.39`. */
  readonly glibcVersion?: string;
  /** 32-bit ARM: the ARM architecture version (6 or 7). */
  readonly armVersion?: number;
  /** macOS: this is Apple Silicon, even if the process itself is x64 (Rosetta). */
  readonly appleSilicon?: boolean;
}

/** No uv build fits this machine. The message names the machine and the version. */
export class UnsupportedUvHostError extends Error {
  override readonly name: string = 'UnsupportedUvHostError';
  constructor(
    readonly host: UvHost,
    readonly version: string,
  ) {
    super(
      `uv ${version} has no build for this machine (${describeHost(host)}). ` +
        'Install uv yourself (https://docs.astral.sh/uv/) and it will be used from PATH.',
    );
  }
}

function describeHost(host: UvHost): string {
  const libc = host.platform === 'linux' ? `, ${host.libc ?? 'unknown libc'}` : '';
  const glibc = host.glibcVersion !== undefined ? ` ${host.glibcVersion}` : '';
  return `${host.platform}-${host.arch}${libc}${host.libc === 'glibc' ? glibc : ''}`;
}

/** The archive kind, read from the asset's file name. */
export function uvArchiveKind(assetName: string): UvArchiveKind {
  if (assetName.endsWith('.zip')) return 'zip';
  if (assetName.endsWith('.tar.gz')) return 'tar.gz';
  throw new Error(`unknown uv archive type: ${assetName}`);
}

/** The executable a target's archive carries. */
export function uvBinName(target: UvTarget): 'uv' | 'uv.exe' {
  return target.includes('-windows-') ? 'uv.exe' : 'uv';
}

/** Browser download URL of a release asset. */
export function uvAssetUrl(release: Pick<UvRelease, 'version' | 'assetName'>): string {
  return `https://github.com/astral-sh/uv/releases/download/${release.version}/${release.assetName}`;
}

/** Linux CPU names as they appear in uv's target triples. */
function linuxCpu(host: UvHost): string | undefined {
  switch (host.arch) {
    case 'x64':
      return 'x86_64';
    case 'arm64':
      return 'aarch64';
    case 'ia32':
      return 'i686';
    case 'arm':
      // uv's armv7 builds need ARMv7; an ARMv6 board (Pi Zero/1) gets the v6 musl build.
      return host.armVersion !== undefined && host.armVersion < 7 ? 'arm' : 'armv7';
    case 'ppc64':
      // Node supports only little-endian ppc64 on Linux.
      return 'powerpc64le';
    case 'riscv64':
      return 'riscv64gc';
    case 's390x':
      return 's390x';
    default:
      return undefined;
  }
}

function linuxGnuTarget(cpu: string): UvTarget | undefined {
  if (cpu === 'arm') return undefined; // uv publishes no glibc ARMv6 build
  if (cpu === 'armv7') return 'armv7-unknown-linux-gnueabihf';
  return `${cpu}-unknown-linux-gnu`;
}

function linuxMuslTarget(cpu: string): UvTarget | undefined {
  if (cpu === 'powerpc64le' || cpu === 's390x') return undefined; // no musl builds
  if (cpu === 'arm' || cpu === 'armv7') return `${cpu}-unknown-linux-musleabihf`;
  return `${cpu}-unknown-linux-musl`;
}

/** `a >= b` for dotted numeric versions (`2.39` vs `2.28`). */
function versionAtLeast(a: string, b: string): boolean {
  const pa = a.split('.').map((n) => Number.parseInt(n, 10));
  const pb = b.split('.').map((n) => Number.parseInt(n, 10));
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const x = Number.isFinite(pa[i]) ? (pa[i] as number) : 0;
    const y = Number.isFinite(pb[i]) ? (pb[i] as number) : 0;
    if (x !== y) return x > y;
  }
  return true;
}

function findAsset(pin: UvPin, target: UvTarget): UvAsset | undefined {
  return pin.assets.find((a) => a.target === target);
}

/**
 * Targets that could run on `host`, best first. The first one the pin carries is
 * the one to install (see {@link uvTargetFor}).
 */
export function uvTargetCandidates(host: UvHost, pin: UvPin = PINNED_UV): UvTarget[] {
  switch (host.platform) {
    case 'darwin':
      if (host.arch === 'arm64' || (host.arch === 'x64' && host.appleSilicon === true)) {
        return ['aarch64-apple-darwin'];
      }
      return host.arch === 'x64' ? ['x86_64-apple-darwin'] : [];
    case 'win32':
      if (host.arch === 'x64') return ['x86_64-pc-windows-msvc'];
      if (host.arch === 'arm64') return ['aarch64-pc-windows-msvc'];
      if (host.arch === 'ia32') return ['i686-pc-windows-msvc'];
      return [];
    case 'linux': {
      const cpu = linuxCpu(host);
      if (cpu === undefined) return [];
      const gnu = linuxGnuTarget(cpu);
      const musl = linuxMuslTarget(cpu);
      const out: UvTarget[] = [];
      if (host.libc === 'glibc' && gnu !== undefined) {
        const min = findAsset(pin, gnu)?.minGlibc;
        const ok =
          host.glibcVersion === undefined ||
          min === undefined ||
          versionAtLeast(host.glibcVersion, min);
        if (ok) out.push(gnu);
      }
      // The musl builds are static: they run on glibc hosts too (uv's own Docker
      // images ship them), so they are the fallback for an old or unknown libc.
      if (musl !== undefined) out.push(musl);
      // A libc we could not read, on a CPU with no static build: the glibc build
      // is the only thing left to try.
      if (host.libc === undefined && gnu !== undefined && musl === undefined) out.push(gnu);
      return out;
    }
    default:
      return [];
  }
}

/** The target to install on `host`. Throws {@link UnsupportedUvHostError} when none fits. */
export function uvTargetFor(host: UvHost, pin: UvPin = PINNED_UV): UvTarget {
  const target = uvTargetCandidates(host, pin).find((t) => findAsset(pin, t) !== undefined);
  if (target === undefined) throw new UnsupportedUvHostError(host, pin.version);
  return target;
}

/** The pinned release for one target triple. Throws when the pin has no such build. */
export function uvReleaseForTarget(target: UvTarget, pin: UvPin = PINNED_UV): UvRelease {
  const asset = findAsset(pin, target);
  if (asset === undefined) throw new Error(`uv ${pin.version} has no pinned build for ${target}`);
  return {
    version: pin.version,
    target: asset.target,
    assetName: asset.assetName,
    binName: uvBinName(asset.target),
    archive: uvArchiveKind(asset.assetName),
    sha256: asset.sha256,
    bytes: asset.bytes,
  };
}

/** The pinned release `host` should install. Throws {@link UnsupportedUvHostError}. */
export function uvReleaseFor(host: UvHost = detectUvHost(), pin: UvPin = PINNED_UV): UvRelease {
  return uvReleaseForTarget(uvTargetFor(host, pin), pin);
}

/** Injectable view of the machine for {@link detectUvHost} (tests). */
export interface UvHostProbe {
  readonly platform?: string;
  readonly arch?: string;
  /** `process.report.getReport()`: its `header.glibcVersionRuntime` names the glibc Node runs on. */
  readonly report?: () => unknown;
  /** List a directory's entry names (Linux musl loader check). */
  readonly listDir?: (dir: string) => readonly string[];
  /** Read a sysctl value on macOS; `undefined` when it cannot be read. */
  readonly sysctl?: (name: string) => string | undefined;
  /** 32-bit ARM version; defaults to Node's `process.config.variables.arm_version`. */
  readonly armVersion?: number;
}

/**
 * The process report, without its network section: in a process with many
 * sockets (Electron main) that section can be slow to build, and only the
 * header is wanted here (the same precaution `detect-libc` takes).
 */
function defaultReport(): unknown {
  const report = process.report as
    | (typeof process.report & { excludeNetwork?: boolean })
    | undefined;
  if (report === undefined) return undefined;
  const before = report.excludeNetwork;
  try {
    report.excludeNetwork = true;
    return report.getReport();
  } catch {
    return undefined;
  } finally {
    report.excludeNetwork = before;
  }
}

function defaultListDir(dir: string): readonly string[] {
  try {
    return readdirSync(dir);
  } catch {
    return [];
  }
}

function defaultSysctl(name: string): string | undefined {
  const bin = existsSync('/usr/sbin/sysctl') ? '/usr/sbin/sysctl' : 'sysctl';
  try {
    return execFileSync(bin, ['-n', name], {
      encoding: 'utf8',
      timeout: 2_000,
      stdio: ['ignore', 'pipe', 'ignore'],
      windowsHide: true,
    }).trim();
  } catch {
    return undefined;
  }
}

function defaultArmVersion(): number | undefined {
  const raw = (process.config?.variables as Record<string, unknown> | undefined)?.arm_version;
  const n = Number(raw);
  return Number.isFinite(n) && n > 0 ? n : undefined;
}

function glibcFromReport(report: unknown): string | undefined {
  if (typeof report !== 'object' || report === null) return undefined;
  const header = (report as { header?: { glibcVersionRuntime?: unknown } }).header;
  const v = header?.glibcVersionRuntime;
  return typeof v === 'string' && /^\d+\.\d+/.test(v) ? v : undefined;
}

let cachedHost: UvHost | undefined;

/**
 * Describe the running machine for asset selection. Cheap after the first call
 * (the real probe is cached); a `probe` argument bypasses the cache (tests).
 */
export function detectUvHost(probe?: UvHostProbe): UvHost {
  if (probe === undefined && cachedHost !== undefined) return cachedHost;
  const p = probe ?? {};
  const platform = p.platform ?? process.platform;
  const arch = p.arch ?? process.arch;
  let host: UvHost = { platform, arch };

  if (platform === 'linux') {
    const glibc = glibcFromReport((p.report ?? defaultReport)());
    if (glibc !== undefined) {
      host = { ...host, libc: 'glibc', glibcVersion: glibc };
    } else {
      const lib = (p.listDir ?? defaultListDir)('/lib');
      if (lib.some((n) => /^ld-musl-.+\.so\.1$/.test(n))) host = { ...host, libc: 'musl' };
    }
    if (arch === 'arm') {
      const v = p.armVersion ?? defaultArmVersion();
      if (v !== undefined) host = { ...host, armVersion: v };
    }
  }

  if (platform === 'darwin') {
    const arm64 =
      arch === 'arm64' || (p.sysctl ?? defaultSysctl)('hw.optional.arm64')?.trim() === '1';
    host = { ...host, appleSilicon: arm64 };
  }

  if (probe === undefined) cachedHost = host;
  return host;
}
