/**
 * A REAL NAME FOR EVERY FLAG. The user (2026-09-13): "don't show for example
 * draft settings or any for that matter as their literal flag names, write
 * real names eg. not -c instead Context Window."
 *
 * The engines' `--help` is the only complete source of their flags, so the
 * panel cannot hand-write every label — it names the ones people reach for
 * and derives the rest from the flag itself, expanding the abbreviations the
 * engines use (`ctx` → context, `ngl` → GPU layers, `ubatch` → micro-batch…).
 * The literal flag stays available in the row's ⓘ, with the engine's own
 * description, for anyone who wants to check what is actually passed.
 */

/** Hand-named flags, keyed by the long form (llama.cpp, then the MLX engines). */
const NAMED: Readonly<Record<string, string>> = {
  '--ctx-size': 'Context window',
  '--n-predict': 'Max reply length',
  '--predict': 'Max reply length',
  '--n-gpu-layers': 'GPU layers',
  '--gpu-layers': 'GPU layers',
  '--threads': 'CPU threads',
  '--threads-batch': 'CPU threads for prefill',
  '--batch-size': 'Prefill batch',
  '--ubatch-size': 'Prefill micro-batch',
  '--flash-attn': 'Flash attention',
  '--cache-type-k': 'KV cache type (keys)',
  '--cache-type-v': 'KV cache type (values)',
  '--cache-ram': 'Prompt cache memory',
  '--cache-reuse': 'Prompt cache reuse',
  '--cache-prompt': 'Prompt caching',
  '--parallel': 'Parallel requests',
  '--cont-batching': 'Continuous batching',
  '--jinja': 'Jinja chat templates',
  '--chat-template': 'Chat template (inline)',
  '--chat-template-file': 'Chat template file',
  '--chat-template-kwargs': 'Chat template variables',
  '--reasoning': 'Thinking',
  '--reasoning-budget': 'Thinking budget',
  '--reasoning-budget-message': 'Thinking budget message',
  '--reasoning-format': 'Thinking output format',
  '--reasoning-preserve': 'Keep thinking in history',
  '--reasoning-effort': 'Thinking effort',
  '--mlock': 'Lock model in memory',
  '--mmap': 'Memory-map the model',
  '--no-mmap': 'Do not memory-map the model',
  '--kv-offload': 'KV cache on GPU',
  '--kv-unified': 'Unified KV cache',
  '--main-gpu': 'Main GPU',
  '--split-mode': 'Multi-GPU split',
  '--tensor-split': 'Tensor split across GPUs',
  '--device': 'Devices',
  '--seed': 'Random seed',
  '--temp': 'Temperature',
  '--top-k': 'Top-K',
  '--top-p': 'Top-P',
  '--min-p': 'Min-P',
  '--typical': 'Typical sampling',
  '--repeat-penalty': 'Repeat penalty',
  '--repeat-last-n': 'Repeat penalty window',
  '--presence-penalty': 'Presence penalty',
  '--frequency-penalty': 'Frequency penalty',
  '--dry-multiplier': 'DRY multiplier',
  '--dry-base': 'DRY base',
  '--dry-allowed-length': 'DRY allowed length',
  '--dry-penalty-last-n': 'DRY window',
  '--dry-sequence-breaker': 'DRY sequence breakers',
  '--dynatemp-range': 'Dynamic temperature range',
  '--dynatemp-exp': 'Dynamic temperature exponent',
  '--mirostat': 'Mirostat',
  '--mirostat-lr': 'Mirostat learning rate',
  '--mirostat-ent': 'Mirostat target entropy',
  '--samplers': 'Sampler order',
  '--sampler-seq': 'Sampler sequence',
  '--grammar': 'Grammar',
  '--grammar-file': 'Grammar file',
  '--json-schema': 'JSON schema',
  '--json-schema-file': 'JSON schema file',
  '--logit-bias': 'Logit bias',
  '--ignore-eos': 'Ignore end of text',
  '--keep': 'Tokens kept on context shift',
  '--context-shift': 'Context shift',
  '--ctx-checkpoints': 'Context checkpoints',
  '--defrag-thold': 'KV defragmentation threshold',
  '--rope-scaling': 'RoPE scaling',
  '--rope-scale': 'RoPE scale',
  '--rope-freq-base': 'RoPE frequency base',
  '--rope-freq-scale': 'RoPE frequency scale',
  '--yarn-ext-factor': 'YaRN extrapolation factor',
  '--yarn-attn-factor': 'YaRN attention factor',
  '--yarn-beta-slow': 'YaRN beta slow',
  '--yarn-beta-fast': 'YaRN beta fast',
  '--yarn-orig-ctx': 'YaRN original context',
  '--mmproj': 'Vision projector',
  '--mmproj-auto': 'Vision projector (auto)',
  '--mmproj-url': 'Vision projector URL',
  '--mmproj-offload': 'Vision projector on GPU',
  '--mmproj-device': 'Vision projector device',
  '--image-max-tokens': 'Image tokens (max)',
  '--image-min-tokens': 'Image tokens (min)',
  '--mtmd-batch-max-tokens': 'Multimodal batch tokens',
  '--media-path': 'Media folder',
  '--model': 'Model file',
  '--model-url': 'Model URL',
  '--hf-file': 'Hugging Face file',
  '--hf-token': 'Hugging Face token',
  '--models-dir': 'Models folder',
  '--models-max': 'Models kept loaded',
  '--models-autoload': 'Autoload models',
  '--models-preset': 'Model presets',
  '--lora': 'LoRA adapter',
  '--lora-scaled': 'LoRA adapter (scaled)',
  '--lora-init-without-apply': 'Load LoRA without applying',
  '--control-vector': 'Control vector',
  '--control-vector-scaled': 'Control vector (scaled)',
  '--control-vector-layer-range': 'Control vector layers',
  '--override-kv': 'Override model metadata',
  '--override-tensor': 'Override tensor placement',
  '--cpu-moe': 'MoE experts on CPU',
  '--n-cpu-moe': 'MoE layers on CPU',
  '--numa': 'NUMA',
  '--cpu-mask': 'CPU mask',
  '--cpu-range': 'CPU range',
  '--cpu-strict': 'Strict CPU placement',
  '--poll': 'Polling',
  '--prio': 'Process priority',
  '--direct-io': 'Direct I/O',
  '--repack': 'Repack weights',
  '--check-tensors': 'Check tensors',
  '--fit': 'Fit to memory',
  '--fit-ctx': 'Fit context to memory',
  '--fit-target': 'Fit memory target',
  '--host': 'Host',
  '--port': 'Port',
  '--path': 'Static files path',
  '--api-prefix': 'API prefix',
  '--api-key': 'API key',
  '--api-key-file': 'API key file',
  '--ssl-key-file': 'SSL key file',
  '--ssl-cert-file': 'SSL certificate',
  '--timeout': 'Request timeout',
  '--threads-http': 'HTTP threads',
  '--cors-origins': 'CORS origins',
  '--cors-methods': 'CORS methods',
  '--cors-headers': 'CORS headers',
  '--cors-credentials': 'CORS credentials',
  '--metrics': 'Prometheus metrics',
  '--slots': 'Slots endpoint',
  '--props': 'Properties endpoint',
  '--slot-save-path': 'Slot save folder',
  '--slot-prompt-similarity': 'Slot prompt similarity',
  '--cache-idle-slots': 'Cache idle slots',
  '--sleep-idle-seconds': 'Sleep when idle',
  '--sse-ping-interval': 'Stream keep-alive',
  '--reuse-port': 'Reuse port',
  '--no-host': 'No network host',
  '--webui': 'Web UI',
  '--alias': 'Model alias',
  '--embedding': 'Embeddings mode',
  '--embd-normalize': 'Normalize embeddings',
  '--embd-output-format': 'Embedding output format',
  '--pooling': 'Pooling',
  '--rerank': 'Reranking mode',
  '--prefill-assistant': 'Continue the assistant message',
  '--skip-chat-parsing': 'Skip chat parsing',
  '--reverse-prompt': 'Stop at prompt',
  '--special': 'Show special tokens',
  '--escape': 'Process escapes',
  '--spm-infill': 'SentencePiece infill',
  '--lookup-cache-static': 'Lookup cache (static)',
  '--lookup-cache-dynamic': 'Lookup cache (dynamic)',
  '--log-file': 'Log file',
  '--log-colors': 'Log colours',
  '--log-disable': 'Disable logging',
  '--log-prefix': 'Log prefix',
  '--log-timestamps': 'Log timestamps',
  '--log-prompts-dir': 'Log prompts to folder',
  '--verbose-prompt': 'Log the prompt',
  '--verbosity': 'Log verbosity',
  '--offline': 'Offline',
  '--rpc': 'RPC servers',
  '--list-devices': 'List devices',
  '--completion-bash': 'Bash completion script',
  '--help': 'Help',
  '--version': 'Version',
  '--backend-sampling': 'Sample on the backend',
  '--adaptive-target': 'Adaptive sampling target',
  '--adaptive-decay': 'Adaptive sampling decay',
  '--checkpoint-min-step': 'Checkpoint step',
  '--load-mode': 'Load mode',
  '--op-offload': 'Offload operations',
  '--perf': 'Performance counters',
  '--agent': 'Agent',
  '--mcp-servers-config': 'MCP servers config',
  '--mcp-servers-json': 'MCP servers JSON',
  '--docker-repo': 'Docker repository',
  // speculative decoding
  '--spec-type': 'Draft method',
  '--spec-default': 'Speculative defaults',
  '--spec-draft-model': 'Draft model',
  '--spec-draft-hf': 'Draft model from Hugging Face',
  '--draft': 'Draft tokens',
  '--draft-max': 'Draft tokens (max)',
  '--draft-min': 'Draft tokens (min)',
  '--spec-draft-n-max': 'Draft tokens (max)',
  '--spec-draft-n-min': 'Draft tokens (min)',
  '--spec-draft-p-min': 'Draft acceptance (min probability)',
  '--spec-draft-p-split': 'Draft split probability',
  '--spec-draft-ngl': 'Draft GPU layers',
  '--spec-draft-device': 'Draft device',
  '--spec-draft-threads': 'Draft CPU threads',
  '--spec-draft-threads-batch': 'Draft CPU threads for prefill',
  '--spec-draft-type-k': 'Draft KV cache type (keys)',
  '--spec-draft-type-v': 'Draft KV cache type (values)',
  '--spec-draft-cpu-moe': 'Draft MoE experts on CPU',
  '--spec-draft-n-cpu-moe': 'Draft MoE layers on CPU',
  '--spec-draft-cpu-mask': 'Draft CPU mask',
  '--spec-draft-cpu-range': 'Draft CPU range',
  '--spec-draft-cpu-strict': 'Draft strict CPU placement',
  '--spec-draft-cpu-mask-batch': 'Draft CPU mask for prefill',
  '--spec-draft-cpu-range-batch': 'Draft CPU range for prefill',
  '--spec-draft-cpu-strict-batch': 'Draft strict CPU placement for prefill',
  '--spec-draft-poll': 'Draft polling',
  '--spec-draft-poll-batch': 'Draft polling for prefill',
  '--spec-draft-prio': 'Draft process priority',
  '--spec-draft-prio-batch': 'Draft priority for prefill',
  '--spec-draft-override-tensor': 'Draft tensor placement',
  '--spec-draft-backend-sampling': 'Draft samples on the backend',
  '--spec-ngram-size-n': 'n-gram size',
  '--spec-ngram-size-m': 'n-gram lookahead',
  '--spec-ngram-min-hits': 'n-gram minimum hits',
  '--spec-ngram-mod-n-min': 'n-gram (mod) minimum',
  '--spec-ngram-mod-n-max': 'n-gram (mod) maximum',
  '--spec-ngram-mod-n-match': 'n-gram (mod) match',
  '--spec-ngram-simple-size-n': 'n-gram (simple) size',
  '--spec-ngram-simple-size-m': 'n-gram (simple) lookahead',
  '--spec-ngram-simple-min-hits': 'n-gram (simple) minimum hits',
  '--spec-ngram-map-k-size-n': 'n-gram map (K) size',
  '--spec-ngram-map-k-size-m': 'n-gram map (K) lookahead',
  '--spec-ngram-map-k-min-hits': 'n-gram map (K) minimum hits',
  '--spec-ngram-map-k4v-size-n': 'n-gram map (K4V) size',
  '--spec-ngram-map-k4v-size-m': 'n-gram map (K4V) lookahead',
  '--spec-ngram-map-k4v-min-hits': 'n-gram map (K4V) minimum hits',
  // MLX engines
  '--max-tokens': 'Max reply length',
  '--max-num-seqs': 'Parallel requests',
  '--max-concurrent-requests': 'Concurrent requests',
  '--kv-cache-dtype': 'KV cache quantization',
  '--kv-cache-quantization': 'KV cache quantization',
  '--kv-cache-quantization-bits': 'KV cache bits',
  '--kv-cache-quantization-group-size': 'KV cache group size',
  '--kv-cache-min-quantize-tokens': 'Quantize KV from',
  '--kv-cache-turboquant': 'KV TurboQuant',
  '--kv-cache-turboquant-bits': 'KV TurboQuant bits',
  '--kv-cache-turboquant-group-size': 'KV TurboQuant group size',
  '--prefill-step-size': 'Prefill chunk',
  '--prefill-batch-size': 'Prefill batch',
  '--completion-batch-size': 'Completion batch',
  '--cache-memory-mb': 'Prompt cache memory',
  '--cache-memory-percent': 'Prompt cache memory (%)',
  '--prefix-cache-size': 'Prefix cache entries',
  '--prefix-cache-index': 'Prefix cache index',
  '--enable-prefix-cache': 'Prefix cache',
  '--disable-prefix-cache': 'No prefix cache',
  '--paged-cache-block-size': 'Paged cache block size',
  '--use-paged-cache': 'Paged cache',
  '--max-cache-blocks': 'Cache blocks (max)',
  '--pin-system-prompt': 'Pin the system prompt',
  '--relocate-mid-conversation-system': 'Keep mid-chat system messages in place',
  '--served-model-name': 'Served model name',
  '--speculative-config': 'Speculative decoding config',
  '--force-spec-decode': 'Force speculative decoding',
  '--no-spec-decode': 'No speculative decoding',
  '--reasoning-parser': 'Thinking parser',
  '--no-reasoning-parser': 'No thinking parser',
  '--no-thinking': 'Thinking off',
  '--tool-call-parser': 'Tool-call parser',
  '--no-tool-call-parser': 'No tool-call parser',
  '--enable-auto-tool-choice': 'Automatic tool choice',
  '--enable-tool-logits-bias': 'Tool logit bias',
  '--gpu-memory-utilization': 'GPU memory use',
  '--metal-cap-kv-bytes-per-token': 'Metal KV bytes per token cap',
  '--resident-memory-limit-gb': 'Resident memory limit',
  '--resident-model-idle-ttl': 'Unload idle model after',
  '--idle-unload-seconds': 'Unload when idle',
  '--idle-cache-clear-seconds': 'Clear cache when idle',
  '--lazy-load': 'Lazy load',
  '--disk-stream': 'Stream weights from disk',
  '--disk-stream-cache-gb': 'Disk stream cache',
  '--force-disk-check': 'Force disk check',
  '--kv-disk-checkpoint-interval': 'KV disk checkpoint interval',
  '--gc-control': 'Garbage-collection control',
  '--no-gc-control': 'No garbage-collection control',
  '--force-hybrid': 'Treat as hybrid model',
  '--no-hybrid': 'Treat as non-hybrid model',
  '--mllm': 'Multimodal',
  '--no-mllm': 'Text only',
  '--enable-audio': 'Audio input',
  '--vision-max-pixels': 'Vision pixels (max)',
  '--vision-min-pixels': 'Vision pixels (min)',
  '--vision-prefill-token-budget': 'Vision prefill token budget',
  '--image-weight-precision': 'Image weight precision',
  '--video-output-dir': 'Video output folder',
  '--embedding-model': 'Embedding model',
  '--embedding-max-length': 'Embedding max length',
  '--embedding-overflow-policy': 'Embedding overflow policy',
  '--default-temperature': 'Default temperature',
  '--default-top-p': 'Default Top-P',
  '--default-top-k': 'Default Top-K',
  '--default-min-p': 'Default Min-P',
  '--default-repetition-penalty': 'Default repeat penalty',
  '--default-presence-penalty': 'Default presence penalty',
  '--default-frequency-penalty': 'Default frequency penalty',
  '--stream-interval': 'Stream interval',
  '--rate-limit': 'Rate limit',
  '--max-request-bytes': 'Request size limit',
  '--trusted-hosts': 'Trusted hosts',
  '--listen-fd': 'Listen on file descriptor',
  '--log-level': 'Log level',
  '--mcp-config': 'MCP config',
  '--watchdog-ppid': 'Exit with parent process',
  '--scheduling-policy': 'Scheduling policy',
  '--scheduling-max-deferrals': 'Scheduling max deferrals',
  '--response-cache-entries': 'Response cache entries',
  '--hybrid-cache-entries': 'Hybrid cache entries',
  '--no-memory-aware-cache': 'No memory-aware cache',
  '--force-openai-harmony-streaming': 'Force Harmony streaming',
  '--no-openai-harmony-streaming': 'No Harmony streaming',
  '--pflash': 'pFlash',
  '--chat-template-args': 'Chat template variables',
  '--enable-thinking': 'Thinking on',
  '--draft-model': 'Draft model',
  '--drafter': 'Drafter',
  '--mode': 'Decoding mode',
  '--model-dir': 'Models folder',
  '--prompt-cache-size': 'Prompt cache entries',
  '--paged-ssd-cache-dir': 'SSD cache folder',
  '--paged-ssd-cache-max-size': 'SSD cache size',
  '--hot-cache-max-size': 'Hot cache size',
  '--hot-cache-write-through': 'Write hot cache through to SSD',
  '--no-cache': 'No cache',
  '--initial-cache-blocks': 'Cache blocks at start',
  '--hf-cache': 'Hugging Face cache',
};

/** Abbreviations the engines use inside flag names, and what they stand for. */
const WORDS: Readonly<Record<string, string>> = {
  ctx: 'context',
  ngl: 'GPU layers',
  gpu: 'GPU',
  cpu: 'CPU',
  kv: 'KV',
  api: 'API',
  url: 'URL',
  ssl: 'SSL',
  cors: 'CORS',
  moe: 'MoE',
  hf: 'Hugging Face',
  mmproj: 'vision projector',
  rope: 'RoPE',
  yarn: 'YaRN',
  numa: 'NUMA',
  rpc: 'RPC',
  sse: 'SSE',
  mcp: 'MCP',
  fd: 'file descriptor',
  spec: 'draft',
  draft: 'draft',
  ubatch: 'micro-batch',
  thold: 'threshold',
  embd: 'embedding',
  fim: 'fill-in-the-middle',
  mtmd: 'multimodal',
  mllm: 'multimodal',
  lr: 'learning rate',
  ent: 'entropy',
  exp: 'exponent',
  temp: 'temperature',
  dir: 'folder',
  mb: 'MB',
  gb: 'GB',
  ppid: 'parent process',
  ttl: 'time to live',
  gc: 'garbage collection',
  seqs: 'sequences',
  num: 'number of',
  dtype: 'data type',
  mem: 'memory',
  max: 'max',
  min: 'min',
  n: 'count',
  k: 'K',
  v: 'V',
  p: 'P',
  io: 'I/O',
  ssd: 'SSD',
  json: 'JSON',
  id: 'ID',
  ui: 'UI',
  http: 'HTTP',
  dry: 'DRY',
  eos: 'end of text',
  lora: 'LoRA',
};

/** `--kv-cache-dtype` → "KV cache data type": the fallback for an unnamed flag. */
export function humanizeFlag(key: string): string {
  const words = key
    .replace(/^-+/, '')
    .split(/[-_]+/)
    .filter((w) => w.length > 0)
    .map((w) => WORDS[w] ?? w)
    // `spec-draft-…` expands to "draft draft …": say it once.
    .filter((w, i, all) => i === 0 || w !== all[i - 1]);
  if (words.length === 0) return key;
  const text = words.join(' ');
  // Capitalise the first letter unless the first word is an acronym already.
  return text.charAt(0) === text.charAt(0).toUpperCase()
    ? text
    : text.charAt(0).toUpperCase() + text.slice(1);
}

/** The label a flag row shows. */
export function flagLabel(flag: {
  readonly key: string;
  readonly aliases?: readonly string[];
}): string {
  const named = NAMED[flag.key] ?? flag.aliases?.map((a) => NAMED[a]).find((n) => n !== undefined);
  return named ?? humanizeFlag(flag.key);
}
