/**
 * ONE CARD FOR EVERYTHING A TURN MAKES — in a studio, and in the middle of a
 * conversation.
 *
 * the user: "design reasonably large inline cards now that make this appear as if
 * it's a chat interface but display videos images and audio in a clean way…
 * (these will all be reused from the same reference for drawing in regular
 * chat)". So there is ONE component, four surfaces, and the chat thread and the
 * three studios all mount it. A picture generated by asking in chat and the same
 * picture generated in the Image Studio are the same object and should not be
 * two different-looking things.
 *
 * WHY THE CONTROLS HIDE. A generated image is the content; a row of buttons
 * permanently welded under it is chrome competing with it, and in a transcript
 * you may have six of these. They come up on hover — and on FOCUS, so the
 * keyboard is not locked out of a pointer-only affordance — and each still
 * animates on its own hover, because a control that appears and then does not
 * respond reads as a picture of a control.
 *
 * WHY EXPAND IS NOT FULLSCREEN. the user: "top left fullscreen that isn't exactly
 * fullscreen but large and centered and blurs background like settings panel."
 * Real fullscreen takes the window and loses the room you were in; this is the
 * app's own dialog treatment — large, centred, the transcript still visibly
 * behind it — so it reads as looking closer at something rather than leaving.
 */
import { type JSX, useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { pdFileUrl } from '../chat/canvas/file-preview';
import { ThreadAudio } from '../chat/ThreadAudio';
import { humanSize, type ThreadMediaItem } from '../chat/thread-media';
import { useModalityStore } from '../state/modality-store';
import { ModelSurface } from './ModelSurface';
import { exportFile, revealFile, startFileDrag } from './media-actions';
import { VideoSurface } from './VideoSurface';

/** The media itself, at whatever size the frame around it gives. */
function Surface({ item, large }: { item: ThreadMediaItem; large: boolean }): JSX.Element {
  const src = pdFileUrl(item.path);
  if (item.kind === 'image') {
    return (
      <img
        className="pd-media-image"
        data-testid="media-image"
        src={src}
        alt={item.name}
        draggable={false}
      />
    );
  }
  if (item.kind === 'video') return <VideoSurface src={src} large={large} testid="media-video" />;
  if (item.kind === 'model') return <ModelSurface src={src} testid="media-model" />;
  return <ThreadAudio src={src} name={item.name} />;
}

function GlyphExpand(): JSX.Element {
  return (
    <svg width="15" height="15" viewBox="0 0 16 16" fill="none" aria-hidden="true">
      <title>Expand</title>
      <path
        d="M6.2 2.5H2.5v3.7M9.8 2.5h3.7v3.7M13.5 9.8v3.7H9.8M2.5 9.8v3.7h3.7"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function GlyphExport(): JSX.Element {
  return (
    <svg width="15" height="15" viewBox="0 0 16 16" fill="none" aria-hidden="true">
      <title>Export</title>
      <path
        d="M8 10.4V2.6M5.2 5.4L8 2.6l2.8 2.8M2.8 10v2.6a.8.8 0 00.8.8h8.8a.8.8 0 00.8-.8V10"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function GlyphCube(): JSX.Element {
  return (
    <svg width="14" height="14" viewBox="0 0 16 16" fill="none" aria-hidden="true">
      <title>Studio</title>
      <path
        d="M8 1.9l5.4 3v6.2L8 14.1l-5.4-3V4.9zM2.6 4.9L8 7.9l5.4-3M8 7.9v6.2"
        stroke="currentColor"
        strokeWidth="1.4"
        strokeLinejoin="round"
      />
    </svg>
  );
}

/** The corner controls. Same set in the card and in the expanded view. */
function Controls({
  item,
  onExpand,
}: {
  item: ThreadMediaItem;
  onExpand?: (() => void) | undefined;
}): JSX.Element {
  const setModality = useModalityStore((s) => s.setView);
  return (
    <>
      {onExpand !== undefined ? (
        <button
          type="button"
          className="pd-media-btn pd-media-btn--tl pd-focusable"
          data-testid="media-expand"
          aria-label="Open larger"
          onClick={onExpand}
        >
          <GlyphExpand />
        </button>
      ) : null}
      {item.kind === 'model' ? (
        /* An inline turntable that cannot escalate is a dead end — this is the
           way out to the room that can actually retopologise and rig it. */
        <button
          type="button"
          className="pd-media-btn pd-media-btn--bl pd-media-btn--wide pd-focusable"
          data-testid="media-open-studio"
          onClick={() => setModality('3d')}
        >
          <GlyphCube />
          Open in studio
        </button>
      ) : null}
      <button
        type="button"
        className="pd-media-btn pd-media-btn--br pd-focusable"
        data-testid="media-export"
        aria-label={`Export ${item.name}`}
        onClick={() => exportFile(item.path, item.name)}
      >
        <GlyphExport />
      </button>
    </>
  );
}

/**
 * The expanded view: large, centred, the room blurred behind it.
 *
 * Deliberately the same treatment as the settings dialog rather than a bespoke
 * one — it is the app's established "look closer at this" gesture, and Escape
 * and click-outside already mean what people expect there.
 */
function Expanded({ item, onClose }: { item: ThreadMediaItem; onClose: () => void }): JSX.Element {
  useEffect(() => {
    const onKey = (e: KeyboardEvent): void => {
      if (e.key === 'Escape') {
        e.stopPropagation();
        onClose();
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [onClose]);

  /*
   * THE APP'S CHROME STANDS DOWN WHILE THIS IS UP.
   *
   * the user, looking at the first version: "no to this thing at the bottom and no
   * to the top bar staying here aswell. no input bar here when expanded." A
   * blurred backdrop still left a recognisable top bar and a composer sitting
   * under the picture, which reads as the app carrying on behind a pane of
   * glass rather than getting out of the way.
   *
   * Faded rather than unmounted, deliberately: removing the composer would
   * reflow the surface behind the blur and drop whatever was typed in it. This
   * is a flag on <body> because the two things to quieten live in completely
   * different subtrees from this one.
   */
  useEffect(() => {
    document.body.setAttribute('data-media-expanded', 'true');
    return () => document.body.removeAttribute('data-media-expanded');
  }, []);

  /*
   * PORTALLED TO THE BODY, and it has to be.
   *
   * The card lives inside the results ScrollArea, and a scroll container that
   * establishes a stacking context (transform, filter, contain — this one does)
   * makes `position: fixed` fix to IT rather than to the viewport. MEASURED: the
   * scrim was clipped at the composer's top edge and the caption under the
   * picture was simply not on screen. z-index cannot fix that; leaving the
   * subtree can.
   */
  return createPortal(
    /*
     * `role="dialog"` + `aria-modal` is not decoration here — it is what stops
     * Escape from doing TWO things. StudioShell also listens for Escape (it
     * leaves the room) and skips when a dialog is up, exactly by looking for
     * this role. Without it, closing an expanded picture also walked you out of
     * the studio, which is the sort of thing you only find by driving it.
     */
    <div
      className="pd-media-scrim"
      data-testid="media-expanded"
      role="dialog"
      aria-modal="true"
      aria-label={item.name}
    >
      {/* The backdrop dismisses. A button rather than a div so Enter and Space
          close it too, without a keyboard shim. */}
      <button type="button" className="pd-media-scrim-hit" aria-label="Close" onClick={onClose} />
      <div className="pd-media-stage" data-kind={item.kind}>
        {/*
          NO CAPTION BAR. the user: "no bottom bar for the image 'fox-real.png'
          bottom bar needs to go". It was a strip of chrome under a picture that
          had just taken the screen, saying a filename you already knew — and the
          card you opened it from says the same thing two inches away. The
          controls float on the media instead.
        */}
        <Surface item={item} large />
        <Controls item={item} onExpand={undefined} />
      </div>
    </div>,
    document.body,
  );
}

export interface MediaCardProps {
  readonly item: ThreadMediaItem;
  /** Bytes, when the caller already knows. Fetched otherwise. */
  readonly bytes?: number;
}

export function MediaCard({ item }: MediaCardProps): JSX.Element {
  const [open, setOpen] = useState(false);
  const [bytes, setBytes] = useState<number | undefined>(undefined);

  /*
   * Size is read from the served response rather than passed in: the tool result
   * only ever named the path, and a caption that says "1.2 MB" is doing the job
   * a caption exists for while one that says nothing is a filename.
   */
  useEffect(() => {
    const ac = new AbortController();
    fetch(pdFileUrl(item.path), { signal: ac.signal })
      .then((r) => r.blob())
      .then((b) => setBytes(b.size))
      .catch(() => undefined);
    return () => ac.abort();
  }, [item.path]);

  return (
    <figure className="pd-media-card" data-kind={item.kind} data-testid="media-card">
      {/*
        Drag is a pointer gesture by nature, which is what the a11y rule warns
        about — the Export button beside it is the same outcome by keyboard.
      */}
      {/* biome-ignore lint/a11y/noStaticElementInteractions: Export is the accessible equivalent. */}
      <div
        className="pd-media-frame"
        draggable
        onDragStart={(e) => startFileDrag(e, item.path)}
        title={`${item.path} — drag me anywhere`}
      >
        <Surface item={item} large={false} />
        <Controls item={item} onExpand={() => setOpen(true)} />
      </div>
      <figcaption className="pd-media-caption">
        <button
          type="button"
          className="pd-media-name pd-focusable"
          data-testid="media-reveal"
          title={`${item.path} — show in Finder`}
          onClick={() => revealFile(item.path)}
        >
          {item.name}
        </button>
        <span className="pd-media-meta">
          {item.kind === 'model' ? '3D' : item.kind}
          {bytes !== undefined ? ` · ${humanSize(bytes)}` : ''}
        </span>
      </figcaption>
      {open ? <Expanded item={item} onClose={() => setOpen(false)} /> : null}
    </figure>
  );
}
