/**
 * ONE CARD FOR EVERYTHING A TURN MAKES — in a studio, and in the middle of a
 * conversation.
 *
 * the user: "design reasonably large inline cards now that make this appear as if
 * it's a chat interface but display videos images and audio in a clean way…
 * (these will all be reused from the same reference for drawing in regular
 * chat)". So there is ONE component, four surfaces, and the chat thread and the
 * three studios all mount it. A picture generated by asking in chat and the same
 * picture generated in the Image Studio are the same object and should not be
 * two different-looking things.
 *
 * WHY THE CONTROLS HIDE. A generated image is the content; a row of buttons
 * permanently welded under it is chrome competing with it, and in a transcript
 * you may have six of these. They come up on hover — and on FOCUS, so the
 * keyboard is not locked out of a pointer-only affordance — and each still
 * animates on its own hover, because a control that appears and then does not
 * respond reads as a picture of a control.
 *
 * WHY EXPAND IS NOT FULLSCREEN. the user: "top left fullscreen that isn't exactly
 * fullscreen but large and centered and blurs background like settings panel."
 * Real fullscreen takes the window and loses the room you were in; this is the
 * app's own dialog treatment — large, centred, the transcript still visibly
 * behind it — so it reads as looking closer at something rather than leaving.
 */
import {
  IconCheck,
  IconCopy,
  IconExpand,
  IconShare,
  IconStudio3d,
  useCopyFeedback,
} from '@pi-desktop/ui';
import { type JSX, type MouseEvent, useEffect, useMemo, useState } from 'react';
import { pdFileUrl } from '../chat/canvas/file-preview';
import { ThreadAudio } from '../chat/ThreadAudio';
import { humanSize, type ThreadMediaItem } from '../chat/thread-media';
import { useModalityStore } from '../state/modality-store';
import { studioFor, useStudioHandoff } from '../state/studio-handoff';
import { ExpandedScrim } from './ExpandedScrim';
import { ModelControls } from './ModelControls';
import { ModelSurface } from './ModelSurface';
import { copyFile, exportFile, revealFile, startFileDrag } from './media-actions';
import { shapeOf } from './media-shapes';
import { createModelView, type ModelView } from './model-view';
import { ImageViewer } from './picture-viewer';
import { VideoSurface } from './VideoSurface';

/*
 * A PICTURE OPENS INTO THE IMAGE VIEWER — the studio-shaped room around one
 * image (ImageViewer.tsx), lazily, through the one entry every surface that
 * shows a picture shares (picture-viewer.tsx).
 */

/** The media itself, at whatever size the frame around it gives. */
function Surface({
  item,
  large,
  view,
}: {
  item: ThreadMediaItem;
  large: boolean;
  /** A 3D card's controls state — shared by its frame and its expanded stage. */
  view?: ModelView;
}): JSX.Element {
  const src = pdFileUrl(item.path);
  /* A picture the waiting card just swept in has a known shape: hold its box
     until this copy decodes, so the handover has no frame at the empty size
     (see media-shapes). */
  const known = item.kind === 'image' ? shapeOf(item.path) : undefined;
  const [decoded, setDecoded] = useState(known === undefined);
  if (item.kind === 'image') {
    return (
      <img
        className="pd-media-image"
        data-testid="media-image"
        src={src}
        alt={item.name}
        draggable={false}
        onLoad={() => setDecoded(true)}
        style={
          decoded || known === undefined
            ? undefined
            : {
                aspectRatio: String(known),
                width: `min(calc(var(--pd-media-max-h) * ${known}), 100%)`,
              }
        }
      />
    );
  }
  if (item.kind === 'video') return <VideoSurface src={src} large={large} testid="media-video" />;
  if (item.kind === 'model') {
    return <ModelSurface src={src} testid="media-model" {...(view ? { view } : {})} />;
  }
  return <ThreadAudio src={src} name={item.name} />;
}

/*
 * The corner glyphs are the shared set (icons.tsx). Expand keeps the user's ↖↘
 * diagonal ("a diagonal arrow pointing up left and down right"): arrows apart
 * along one diagonal say the thing is about to grow, where a four-corner bracket
 * says "crop". They lie on the picture, so .pd-media-btn draws them heavier.
 */
/** The corner controls. Same set in the card and in the expanded view. */
function Controls({
  item,
  onExpand,
}: {
  item: ThreadMediaItem;
  onExpand?: (() => void) | undefined;
}): JSX.Element {
  const setModality = useModalityStore((s) => s.setView);
  const view = useModalityStore((s) => s.view);
  const offerToStudio = useStudioHandoff((s) => s.offer);
  const target = studioFor(item.kind);
  /*
   * THE SAME CARD MEANS DIFFERENT THINGS IN DIFFERENT ROOMS.
   *
   * In the transcript, the useful move is to take this somewhere it can be
   * worked on. Standing in that room already, "Open in studio" would be a
   * button that goes where you are — so it becomes "Use as input", which is the
   * iterate loop (that, but at sunset — then again), and the trip BACK to the
   * conversation is offered instead.
   */
  const inItsStudio = view === target;
  const { copied, copy } = useCopyFeedback();
  return (
    <>
      {onExpand !== undefined ? (
        <button
          type="button"
          className="pd-media-btn pd-media-btn--tl pd-focusable"
          data-testid="media-expand"
          aria-label="Open larger"
          onClick={onExpand}
        >
          <IconExpand size={19} />
        </button>
      ) : null}
      {/*
        EVERY KIND CAN ESCALATE, AND IT TAKES THE MEDIA WITH IT.

        This was on the MESH alone, and even there it only switched the view —
        you arrived in an empty 3D studio standing next to the thing you had
        just been looking at. A picture, a clip and a sound offered nothing at
        all. the user, round 2: "all types of media handoff into studios and
        editing." The prompt and seed ride along, because the first thing anyone
        does with a generated picture is ask for it again slightly differently.
      */}
      <button
        type="button"
        className="pd-media-btn pd-media-btn--bl pd-media-btn--wide pd-focusable"
        data-testid="media-open-studio"
        onClick={() => {
          offerToStudio(target, {
            path: item.path,
            name: item.name,
            kind: item.kind,
            ...(item.prompt !== undefined ? { prompt: item.prompt } : {}),
            ...(item.seed !== undefined ? { seed: item.seed } : {}),
            ...(item.model !== undefined ? { model: item.model } : {}),
          });
          if (!inItsStudio) setModality(target === '3d' ? '3d' : target);
        }}
      >
        {item.kind === 'model' && !inItsStudio ? <IconStudio3d size={14} /> : null}
        {inItsStudio ? 'Use as input' : 'Open in studio'}
      </button>
      {/*
        COPY. The top-right corner used to send the result to the conversation
        (send-to-chat.ts still does that for the studios' "Use as input" flow);
        the user (2026-09-17): "the 'take to a new chat' button in the top right of
        each card should just be replaced with a copy button that instantly
        copies it to clipboard." A picture goes as pixels, the rest as the file.
      */}
      <button
        type="button"
        className="pd-media-btn pd-media-btn--tr pd-focusable"
        data-testid="media-copy"
        aria-label={copied ? 'Copied' : `Copy ${item.name}`}
        title={copied ? 'Copied' : 'Copy'}
        onClick={() => {
          void copyFile(item.path).then((ok) => {
            if (ok) copy();
          });
        }}
      >
        {copied ? <IconCheck size={18} /> : <IconCopy size={18} />}
      </button>
      <button
        type="button"
        className="pd-media-btn pd-media-btn--br pd-focusable"
        data-testid="media-export"
        aria-label={`Export ${item.name}`}
        onClick={() => exportFile(item.path, item.name)}
      >
        <IconShare size={18} />
      </button>
    </>
  );
}

/**
 * The expanded view: large, centred, the room blurred behind it.
 *
 * Deliberately the same treatment as the settings dialog rather than a bespoke
 * one — it is the app's established "look closer at this" gesture, and Escape
 * and click-outside already mean what people expect there. The scrim itself now
 * lives in {@link ExpandedScrim}, because the user asked for the same gesture on
 * INPUT media (an attachment in the composer, a pasted-text card in a user
 * message) and two near-identical overlays is how they drift apart.
 */
function Expanded({
  item,
  onClose,
  view,
}: {
  item: ThreadMediaItem;
  onClose: () => void;
  view?: ModelView;
}): JSX.Element {
  return (
    <ExpandedScrim label={item.name} onClose={onClose} stageKind={item.kind}>
      {/*
        NO CAPTION BAR. the user: "no bottom bar for the image 'fox-real.png'
        bottom bar needs to go". It was a strip of chrome under a picture that
        had just taken the screen, saying a filename you already knew — and the
        card you opened it from says the same thing two inches away. The
        controls float on the media instead.
      */}
      <Surface item={item} large {...(view ? { view } : {})} />
      <Controls item={item} onExpand={undefined} />
    </ExpandedScrim>
  );
}

export interface MediaCardProps {
  readonly item: ThreadMediaItem;
  /** Bytes, when the caller already knows. Fetched otherwise. */
  readonly bytes?: number;
}

export function MediaCard({ item }: MediaCardProps): JSX.Element {
  const [open, setOpen] = useState(false);
  const [bytes, setBytes] = useState<number | undefined>(undefined);
  /*
   * A 3D CARD'S FEW CONTROLS (model-view.ts) — made once per card, so the
   * strip under the viewport and the expanded stage show the same shading,
   * and a rig turned on stays on when you look closer.
   */
  const modelView = useMemo(
    () => (item.kind === 'model' ? createModelView() : undefined),
    [item.kind],
  );

  /*
   * Size is read from the served response rather than passed in: the tool result
   * only ever named the path, and a caption that says "1.2 MB" is doing the job
   * a caption exists for while one that says nothing is a filename.
   */
  useEffect(() => {
    const ac = new AbortController();
    fetch(pdFileUrl(item.path), { signal: ac.signal })
      .then((r) => r.blob())
      .then((b) => setBytes(b.size))
      .catch(() => undefined);
    return () => ac.abort();
  }, [item.path]);

  /*
   * A SOUND IS A STRIP, AND A STRIP HAS NO CORNERS TO SPARE.
   *
   * The controls float in the four corners of a picture because a picture has
   * room under them. The audio card is 50px tall (the user, 2026-09-14: "shorten
   * this card vertically") — the transport IS the frame — so a corner control
   * lands on the play button, and MEASURED, Playwright could not press Play on
   * hover: "Use as input" intercepts pointer events. So for a sound the same
   * controls stand BESIDE the strip, in the row with it, and fade in with the
   * same hover.
   */
  const beside = item.kind === 'audio';
  /*
   * CLICKING THE PICTURE OPENS IT. the user: "clicking on a card (eg image once
   * finished generating) does not expand/open it." Only the corner button did,
   * and only once you had found it on hover. A picture only — a clip's frame is
   * its transport, a model's is a viewport you drag to turn, a sound's is a
   * scrubber — and never a click that was really one of the corner controls.
   */
  const openOnClick =
    item.kind === 'image'
      ? (e: MouseEvent<HTMLDivElement>) => {
          if ((e.target as HTMLElement).closest('button') !== null) return;
          setOpen(true);
        }
      : undefined;
  const frame = (
    /*
      Drag is a pointer gesture by nature, which is what the a11y rule warns
      about — the Export button beside it is the same outcome by keyboard, and
      "Open larger" is the keyboard's route to the click.
    */
    // biome-ignore lint/a11y/noStaticElementInteractions: Export and Open larger are the accessible equivalents.
    // biome-ignore lint/a11y/useKeyWithClickEvents: Open larger is the keyboard route to the same view.
    <div
      className="pd-media-frame"
      draggable
      onDragStart={(e) => startFileDrag(e, item.path)}
      onClick={openOnClick}
      data-opens={openOnClick !== undefined ? 'true' : undefined}
      title={
        openOnClick !== undefined
          ? `Click to open · drag to save · ${item.path}`
          : `Drag to save · ${item.path}`
      }
    >
      <Surface item={item} large={false} {...(modelView ? { view: modelView } : {})} />
      {beside ? null : <Controls item={item} onExpand={() => setOpen(true)} />}
    </div>
  );
  return (
    <figure className="pd-media-card" data-kind={item.kind} data-testid="media-card">
      {beside ? (
        <div className="pd-media-strip">
          {frame}
          <div className="pd-media-beside" data-testid="media-beside">
            <Controls item={item} onExpand={() => setOpen(true)} />
          </div>
        </div>
      ) : (
        frame
      )}
      {/* the user: "below the card itself show some basic controls" — the strip
          sits between the viewport and the caption, as wide as the frame. */}
      {modelView !== undefined ? <ModelControls view={modelView} /> : null}
      <figcaption className="pd-media-caption">
        <button
          type="button"
          className="pd-media-name pd-focusable"
          data-testid="media-reveal"
          title={`Show in Finder · ${item.path}`}
          onClick={() => revealFile(item.path)}
        >
          {item.name}
        </button>
        <span className="pd-media-meta">
          {item.kind === 'model' ? '3D' : item.kind}
          {bytes !== undefined ? ` · ${humanSize(bytes)}` : ''}
        </span>
      </figcaption>
      {open && item.kind === 'image' ? (
        <ImageViewer item={item} onClose={() => setOpen(false)} />
      ) : open ? (
        <Expanded
          item={item}
          onClose={() => setOpen(false)}
          {...(modelView ? { view: modelView } : {})}
        />
      ) : null}
    </figure>
  );
}
