/**
 * ONE CARD FOR EVERYTHING A TURN MAKES — in a studio, and in the middle of a
 * conversation.
 *
 * the user: "design reasonably large inline cards now that make this appear as if
 * it's a chat interface but display videos images and audio in a clean way…
 * (these will all be reused from the same reference for drawing in regular
 * chat)". So there is ONE component, four surfaces, and the chat thread and the
 * three studios all mount it. A picture generated by asking in chat and the same
 * picture generated in the Image Studio are the same object and should not be
 * two different-looking things.
 *
 * WHY THE CONTROLS HIDE. A generated image is the content; a row of buttons
 * permanently welded under it is chrome competing with it, and in a transcript
 * you may have six of these. They come up on hover — and on FOCUS, so the
 * keyboard is not locked out of a pointer-only affordance — and each still
 * animates on its own hover, because a control that appears and then does not
 * respond reads as a picture of a control.
 *
 * WHY EXPAND IS NOT FULLSCREEN. the user: "top left fullscreen that isn't exactly
 * fullscreen but large and centered and blurs background like settings panel."
 * Real fullscreen takes the window and loses the room you were in; this is the
 * app's own dialog treatment — large, centred, the transcript still visibly
 * behind it — so it reads as looking closer at something rather than leaving.
 */
import { type JSX, useEffect, useState } from 'react';
import { pdFileUrl } from '../chat/canvas/file-preview';
import { ThreadAudio } from '../chat/ThreadAudio';
import { humanSize, type ThreadMediaItem } from '../chat/thread-media';
import { useModalityStore } from '../state/modality-store';
import { studioFor, useStudioHandoff } from '../state/studio-handoff';
import { ExpandedScrim } from './ExpandedScrim';
import { ModelSurface } from './ModelSurface';
import { exportFile, revealFile, startFileDrag } from './media-actions';
import { sendToChat } from './send-to-chat';
import { VideoSurface } from './VideoSurface';

/** The media itself, at whatever size the frame around it gives. */
function Surface({ item, large }: { item: ThreadMediaItem; large: boolean }): JSX.Element {
  const src = pdFileUrl(item.path);
  if (item.kind === 'image') {
    return (
      <img
        className="pd-media-image"
        data-testid="media-image"
        src={src}
        alt={item.name}
        draggable={false}
      />
    );
  }
  if (item.kind === 'video') return <VideoSurface src={src} large={large} testid="media-video" />;
  if (item.kind === 'model') return <ModelSurface src={src} testid="media-model" />;
  return <ThreadAudio src={src} name={item.name} />;
}

/*
 * TWO ARROWS ON THE ↖↘ DIAGONAL. the user: "a diagonal arrow pointing up left and
 * down right". The four-corner bracket it replaced is the "crop" mark — it says
 * frame this, not open this bigger. Arrows pointing away from each other along
 * one diagonal say the thing is about to grow, which is what the button does.
 */
function GlyphExpand(): JSX.Element {
  return (
    <svg width="19" height="19" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <title>Expand</title>
      <path
        /* Heads at the TOP-LEFT and BOTTOM-RIGHT — the ↖↘ diagonal the user asked
           for. Drawn the other way round first, which is the same icon on the
           other diagonal and reads as a different gesture entirely. */
        d="M9.6 3.6H3.6V9.6M3.6 3.6L10.3 10.3M14.4 20.4H20.4V14.4M20.4 20.4L13.7 13.7"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function GlyphExport(): JSX.Element {
  return (
    <svg width="18" height="18" viewBox="0 0 16 16" fill="none" aria-hidden="true">
      <title>Export</title>
      <path
        d="M8 10.4V2.6M5.2 5.4L8 2.6l2.8 2.8M2.8 10v2.6a.8.8 0 00.8.8h8.8a.8.8 0 00.8-.8V10"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

/** Speech bubble with an arrow going INTO it — back to the conversation. */
function GlyphToChat(): JSX.Element {
  return (
    <svg width="18" height="18" viewBox="0 0 16 16" fill="none" aria-hidden="true">
      <title>Send to chat</title>
      <path
        d="M2.4 5.1a1.6 1.6 0 011.6-1.6h8a1.6 1.6 0 011.6 1.6v4.2a1.6 1.6 0 01-1.6 1.6H7.1L4.2 13.3v-2.4h-.2a1.6 1.6 0 01-1.6-1.6z"
        stroke="currentColor"
        strokeWidth="1.4"
        strokeLinejoin="round"
      />
      <path
        d="M8 4.6v3.6M6.3 6.7L8 8.4l1.7-1.7"
        stroke="currentColor"
        strokeWidth="1.4"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function GlyphCube(): JSX.Element {
  return (
    <svg width="14" height="14" viewBox="0 0 16 16" fill="none" aria-hidden="true">
      <title>Studio</title>
      <path
        d="M8 1.9l5.4 3v6.2L8 14.1l-5.4-3V4.9zM2.6 4.9L8 7.9l5.4-3M8 7.9v6.2"
        stroke="currentColor"
        strokeWidth="1.4"
        strokeLinejoin="round"
      />
    </svg>
  );
}

/** The corner controls. Same set in the card and in the expanded view. */
function Controls({
  item,
  onExpand,
}: {
  item: ThreadMediaItem;
  onExpand?: (() => void) | undefined;
}): JSX.Element {
  const setModality = useModalityStore((s) => s.setView);
  const view = useModalityStore((s) => s.view);
  const offerToStudio = useStudioHandoff((s) => s.offer);
  const target = studioFor(item.kind);
  /*
   * THE SAME CARD MEANS DIFFERENT THINGS IN DIFFERENT ROOMS.
   *
   * In the transcript, the useful move is to take this somewhere it can be
   * worked on. Standing in that room already, "Open in studio" would be a
   * button that goes where you are — so it becomes "Use as input", which is the
   * iterate loop (that, but at sunset — then again), and the trip BACK to the
   * conversation is offered instead.
   */
  const inItsStudio = view === target;
  return (
    <>
      {onExpand !== undefined ? (
        <button
          type="button"
          className="pd-media-btn pd-media-btn--tl pd-focusable"
          data-testid="media-expand"
          aria-label="Open larger"
          onClick={onExpand}
        >
          <GlyphExpand />
        </button>
      ) : null}
      {/*
        EVERY KIND CAN ESCALATE, AND IT TAKES THE MEDIA WITH IT.

        This was on the MESH alone, and even there it only switched the view —
        you arrived in an empty 3D studio standing next to the thing you had
        just been looking at. A picture, a clip and a sound offered nothing at
        all. the user, round 2: "all types of media handoff into studios and
        editing." The prompt and seed ride along, because the first thing anyone
        does with a generated picture is ask for it again slightly differently.
      */}
      <button
        type="button"
        className="pd-media-btn pd-media-btn--bl pd-media-btn--wide pd-focusable"
        data-testid="media-open-studio"
        onClick={() => {
          offerToStudio(target, {
            path: item.path,
            name: item.name,
            kind: item.kind,
            ...(item.prompt !== undefined ? { prompt: item.prompt } : {}),
            ...(item.seed !== undefined ? { seed: item.seed } : {}),
            ...(item.model !== undefined ? { model: item.model } : {}),
          });
          if (!inItsStudio) setModality(target === '3d' ? '3d' : target);
        }}
      >
        {item.kind === 'model' && !inItsStudio ? <GlyphCube /> : null}
        {inItsStudio ? 'Use as input' : 'Open in studio'}
      </button>
      {/*
        BACK TO THE CONVERSATION. Only offered from inside a studio: in the
        transcript this result is already there, and a button that sends a thing
        to where it is teaches people the controls are decorative. A picture
        goes as an attachment the model can see; anything else goes as its path,
        which is what the model can actually act on. See send-to-chat.ts.
      */}
      {inItsStudio ? (
        <button
          type="button"
          className="pd-media-btn pd-media-btn--tr pd-focusable"
          data-testid="media-send-chat"
          aria-label={`Send ${item.name} to the conversation`}
          onClick={() => {
            void sendToChat({ path: item.path, name: item.name, kind: item.kind });
          }}
        >
          <GlyphToChat />
        </button>
      ) : null}
      <button
        type="button"
        className="pd-media-btn pd-media-btn--br pd-focusable"
        data-testid="media-export"
        aria-label={`Export ${item.name}`}
        onClick={() => exportFile(item.path, item.name)}
      >
        <GlyphExport />
      </button>
    </>
  );
}

/**
 * The expanded view: large, centred, the room blurred behind it.
 *
 * Deliberately the same treatment as the settings dialog rather than a bespoke
 * one — it is the app's established "look closer at this" gesture, and Escape
 * and click-outside already mean what people expect there. The scrim itself now
 * lives in {@link ExpandedScrim}, because the user asked for the same gesture on
 * INPUT media (an attachment in the composer, a pasted-text card in a user
 * message) and two near-identical overlays is how they drift apart.
 */
function Expanded({ item, onClose }: { item: ThreadMediaItem; onClose: () => void }): JSX.Element {
  return (
    <ExpandedScrim label={item.name} onClose={onClose} stageKind={item.kind}>
      {/*
        NO CAPTION BAR. the user: "no bottom bar for the image 'fox-real.png'
        bottom bar needs to go". It was a strip of chrome under a picture that
        had just taken the screen, saying a filename you already knew — and the
        card you opened it from says the same thing two inches away. The
        controls float on the media instead.
      */}
      <Surface item={item} large />
      <Controls item={item} onExpand={undefined} />
    </ExpandedScrim>
  );
}

export interface MediaCardProps {
  readonly item: ThreadMediaItem;
  /** Bytes, when the caller already knows. Fetched otherwise. */
  readonly bytes?: number;
}

export function MediaCard({ item }: MediaCardProps): JSX.Element {
  const [open, setOpen] = useState(false);
  const [bytes, setBytes] = useState<number | undefined>(undefined);

  /*
   * Size is read from the served response rather than passed in: the tool result
   * only ever named the path, and a caption that says "1.2 MB" is doing the job
   * a caption exists for while one that says nothing is a filename.
   */
  useEffect(() => {
    const ac = new AbortController();
    fetch(pdFileUrl(item.path), { signal: ac.signal })
      .then((r) => r.blob())
      .then((b) => setBytes(b.size))
      .catch(() => undefined);
    return () => ac.abort();
  }, [item.path]);

  return (
    <figure className="pd-media-card" data-kind={item.kind} data-testid="media-card">
      {/*
        Drag is a pointer gesture by nature, which is what the a11y rule warns
        about — the Export button beside it is the same outcome by keyboard.
      */}
      {/* biome-ignore lint/a11y/noStaticElementInteractions: Export is the accessible equivalent. */}
      <div
        className="pd-media-frame"
        draggable
        onDragStart={(e) => startFileDrag(e, item.path)}
        title={`Drag to save · ${item.path}`}
      >
        <Surface item={item} large={false} />
        <Controls item={item} onExpand={() => setOpen(true)} />
      </div>
      <figcaption className="pd-media-caption">
        <button
          type="button"
          className="pd-media-name pd-focusable"
          data-testid="media-reveal"
          title={`Show in Finder · ${item.path}`}
          onClick={() => revealFile(item.path)}
        >
          {item.name}
        </button>
        <span className="pd-media-meta">
          {item.kind === 'model' ? '3D' : item.kind}
          {bytes !== undefined ? ` · ${humanSize(bytes)}` : ''}
        </span>
      </figcaption>
      {open ? <Expanded item={item} onClose={() => setOpen(false)} /> : null}
    </figure>
  );
}
