import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  colorFromToken,
  decodeOmniSvg,
  decodeOmniSvgPartial,
  loopStart,
  OMNISVG_4B,
} from './omnisvg-decode';

const here = path.dirname(fileURLToPath(import.meta.url));
const fixture = (name: string) => path.join(here, 'fixtures', name);
const ids = (name: string): number[] => JSON.parse(readFileSync(fixture(name), 'utf8'));
const golden = (name: string): string => readFileSync(fixture(name), 'utf8').trim();

/*
 * THE GOLDEN FILES CAME FROM THEIR DECODER. The ids were generated by the
 * Q8_0 GGUF under llama-server; the .svg beside each was written by OmniSVG's
 * own tokenizer.py + deepsvg from exactly those ids. Byte-equality here is
 * the whole claim that this port is faithful.
 */
describe('OmniSVG token decoding — against their decoder', () => {
  it('reproduces the heart byte for byte', () => {
    const out = decodeOmniSvg(ids('omnisvg-heart.ids.json'));
    expect(out?.svg).toBe(golden('omnisvg-heart.golden.svg'));
    expect(out?.paths).toBe(1);
  });

  it('reproduces the fox (curves, multiple sub-paths) byte for byte', () => {
    const out = decodeOmniSvg(ids('omnisvg-fox.ids.json'));
    expect(out?.svg).toBe(golden('omnisvg-fox.golden.svg'));
  });

  it('takes the raw completion tokens as-is: leading BOS, trailing EOS', () => {
    const raw = ids('omnisvg-heart.ids.json');
    expect(raw[0]).toBe(OMNISVG_4B.bos);
    expect(raw[raw.length - 1]).toBe(OMNISVG_4B.eos);
  });

  it('a PREFIX decodes to the shapes finished so far, with the one being drawn as an outline', () => {
    const all = ids('omnisvg-fox.ids.json');
    const whole = decodeOmniSvgPartial(all);
    expect(whole?.svg).toBe(golden('omnisvg-fox.golden.svg'));
    expect(whole?.drawing).toBe(false);
    // Cut mid-way: fewer finished paths than the whole, every one of them a
    // path the final file has, and an outline for the shape in progress.
    const half = decodeOmniSvgPartial(all.slice(0, Math.floor(all.length * 0.55)));
    expect(half).not.toBeNull();
    expect(half?.paths).toBeLessThan(whole?.paths ?? 0);
    for (const m of (half?.svg ?? '').matchAll(/<path fill="(#[0-9a-f]{6})"[^>]*d="([^"]+)"/g)) {
      expect(whole?.svg).toContain(`d="${m[2]}"`);
    }
    if (half?.drawing === true) expect(half.svg).toContain('stroke="#7a8190"');
    // Too short to hold a single command: nothing yet.
    expect(decodeOmniSvgPartial(all.slice(0, 3))).toBeNull();
  });

  it('returns null rather than an empty file when nothing decodes', () => {
    expect(decodeOmniSvg([OMNISVG_4B.bos, OMNISVG_4B.eos])).toBeNull();
    expect(decodeOmniSvg([1, 2, 3])).toBeNull();
  });
});

describe('colour tokens', () => {
  it('maps the sentinels and the 12-bit palette as token_to_color does', () => {
    expect(colorFromToken(40_010)).toBe('none');
    expect(colorFromToken(40_011)).toBe('currentColor');
    expect(colorFromToken(40_012)).toBe('#000000'); // index 0
    expect(colorFromToken(40_012 + 0xfff)).toBe('#ffffff');
    expect(colorFromToken(40_012 + 0xf25)).toBe('#ff2255'); // the heart's fill
  });

  it('greys out an index past the palette', () => {
    expect(colorFromToken(40_012 + 4_098)).toBe('#808080');
  });
});

describe('loopStart — a runaway repeat in the stream', () => {
  // A drawing: distinct ids, then the measured failure — one 4-id command
  // (a curve of no length) over and over.
  const drawing = Array.from({ length: 40 }, (_, i) => 1000 + i);
  const curve = [7, 501, 501, 501];

  it('finds where the repeated block first starts, and keeps the drawing before it', () => {
    const ids = [...drawing, ...Array.from({ length: 20 }, () => curve).flat()];
    expect(loopStart(ids)).toBe(40);
  });

  it('waits for enough repeats: eleven copies are not yet a loop, twelve are', () => {
    expect(loopStart([...drawing, ...Array.from({ length: 11 }, () => curve).flat()])).toBe(-1);
    expect(loopStart([...drawing, ...Array.from({ length: 12 }, () => curve).flat()])).toBe(40);
  });

  it('sees a one-id stutter and a longer block alike', () => {
    expect(loopStart([...drawing, ...Array(12).fill(9)])).toBe(40);
    const block = Array.from({ length: 20 }, (_, i) => 3000 + i);
    expect(loopStart([...drawing, ...Array.from({ length: 12 }, () => block).flat()])).toBe(40);
  });

  it('never calls a drawing that repeats a shape once or twice a loop', () => {
    const shape = Array.from({ length: 30 }, (_, i) => 2000 + i);
    expect(loopStart([...drawing, ...shape, ...shape, ...shape])).toBe(-1);
    expect(loopStart(drawing)).toBe(-1);
    expect(loopStart([])).toBe(-1);
  });
});
