import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { colorFromToken, decodeOmniSvg, OMNISVG_4B } from './omnisvg-decode';

const here = path.dirname(fileURLToPath(import.meta.url));
const fixture = (name: string) => path.join(here, 'fixtures', name);
const ids = (name: string): number[] => JSON.parse(readFileSync(fixture(name), 'utf8'));
const golden = (name: string): string => readFileSync(fixture(name), 'utf8').trim();

/*
 * THE GOLDEN FILES CAME FROM THEIR DECODER. The ids were generated by the
 * Q8_0 GGUF under llama-server; the .svg beside each was written by OmniSVG's
 * own tokenizer.py + deepsvg from exactly those ids. Byte-equality here is
 * the whole claim that this port is faithful.
 */
describe('OmniSVG token decoding — against their decoder', () => {
  it('reproduces the heart byte for byte', () => {
    const out = decodeOmniSvg(ids('omnisvg-heart.ids.json'));
    expect(out?.svg).toBe(golden('omnisvg-heart.golden.svg'));
    expect(out?.paths).toBe(1);
  });

  it('reproduces the fox (curves, multiple sub-paths) byte for byte', () => {
    const out = decodeOmniSvg(ids('omnisvg-fox.ids.json'));
    expect(out?.svg).toBe(golden('omnisvg-fox.golden.svg'));
  });

  it('takes the raw completion tokens as-is: leading BOS, trailing EOS', () => {
    const raw = ids('omnisvg-heart.ids.json');
    expect(raw[0]).toBe(OMNISVG_4B.bos);
    expect(raw[raw.length - 1]).toBe(OMNISVG_4B.eos);
  });

  it('returns null rather than an empty file when nothing decodes', () => {
    expect(decodeOmniSvg([OMNISVG_4B.bos, OMNISVG_4B.eos])).toBeNull();
    expect(decodeOmniSvg([1, 2, 3])).toBeNull();
  });
});

describe('colour tokens', () => {
  it('maps the sentinels and the 12-bit palette as token_to_color does', () => {
    expect(colorFromToken(40_010)).toBe('none');
    expect(colorFromToken(40_011)).toBe('currentColor');
    expect(colorFromToken(40_012)).toBe('#000000'); // index 0
    expect(colorFromToken(40_012 + 0xfff)).toBe('#ffffff');
    expect(colorFromToken(40_012 + 0xf25)).toBe('#ff2255'); // the heart's fill
  });

  it('greys out an index past the palette', () => {
    expect(colorFromToken(40_012 + 4_098)).toBe('#808080');
  });
});
