import { call, done, sleep } from './mac-drive.mjs';
import { execFile } from 'node:child_process';
const osa = (s) => new Promise((r) => execFile('osascript', ['-e', s], () => r()));
await osa('tell application "TextEdit" to quit saving no');
await sleep(1500);
await osa('tell application "TextEdit" to launch');
await sleep(2000);
const pid = (await call('windows', { app: 'TextEdit' })).pid;
await call('menuClick', { pid, path: 'File > New' });
await sleep(1200);
const snap = await call('snapshot', { pid });
const area = (snap.elements ?? []).find((e) => e.role === 'AXTextArea');
await call('type', { pid, index: area.index, text: 'activation test', append: true });
await sleep(600);
console.log('background Save:', JSON.stringify(await call('menuClick', { pid, path: 'File > Save' })).slice(0, 420));
console.log('frontmost after:', (await call('frontmost')).app);
console.log('\nactivate Save:', JSON.stringify(await call('menuClick', { pid, path: 'File > Save', activate: true })).slice(0, 420));
await sleep(1200);
const s2 = await call('snapshot', { pid });
console.log('dialog:', JSON.stringify(s2.dialog));
console.log('sheet controls:', JSON.stringify((s2.elements ?? []).filter((e) => e.win === s2.dialog?.windowId).map((e) => [e.index, e.role, e.name])));
console.log('frontmost after activate:', (await call('frontmost')).app);
done(); process.exit(0);
